#ifndef TOKENS_H
#define TOKENS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef uint8_t fbgc_token;

typedef struct {
	fbgc_token tokencode;
	const char * name;
}token_struct;


//TOKENS_BEGIN
//Autogenerated by helper/token_creator.py
#define UNKNOWN 0 // Begin with unknown
#define NIL 1 // null or none
#define LOGIC 2 // logical true or false
#define INT 3 // int class
#define DOUBLE 4 // double class
#define COMPLEX 5 // complex class
#define STRING 6 // string class
#define MATRIX 7 // matrix class
#define TUPLE 8 // tuple class
#define CSTRING 9 // raw c strings without length
#define CFUN 10 // c function
#define FUN 11 // builtin fbgc function
#define CSTRUCT 12 // 
#define IDENTIFIER 13 // identifiers
#define RANGE 14 // range obj
#define MONATRIX 15 //
#define NUPLE 16 //
#define MONUPLE 17 //
#define ARRAY 18 //
#define LINKED_LIST 19 //
#define CMODULE 20 //
#define GARBAGE 21 //
#define FIELD 22 //
#define END 23 // end
#define FUN_MAKE 24 //
#define ELIF 25 //
#define ELSE 26 //
#define WHILE 27 //
#define FOR 28 //
#define BREAK 29 //
#define CONT 30 //
#define LOAD 31 //
#define IF 32 //
#define RETURN 33 //
#define NEWLINE 34 //
#define LPARA 35 // (
#define RPARA 36 // )
#define LBRACK 37 // [
#define RBRACK 38 // ]
#define LBRACE 39 // {
#define RBRACE 40 // }
#define UMINUS 41 // -
#define UPLUS 42 // +
#define TILDE 43 // ~ set1 starts from here
#define COLON 44 // :
#define COMMA 45 // ,
#define DOT 46 // .
#define SEMICOLON 47 // ; -- set1 finish
#define R_SHIFT 48 // >> assignment and binary operators start from here
#define L_SHIFT 49 // <<
#define STARSTAR 50 // **
#define SLASHSLASH 51 // //
#define PLUS 52 // +
#define MINUS 53 // -
#define STAR 54 // *
#define SLASH 55 // /
#define CARET 56 // ^
#define PERCENT 57 // % assignment finish
#define LO_EQ 58 // <=
#define GR_EQ 59 // >=
#define EQ_EQ 60 // ==
#define NOT_EQ 61 // !=
#define LOWER 62 // <
#define GREATER 63 // >
#define PIPE 64 // |
#define AMPERSAND 65 // & binary finish
#define EXCLAMATION 66 // !
#define ASSIGN 67 // = assignment ops start from here
#define R_SHIFT_ASSIGN 68 // >>=
#define L_SHIFT_ASSIGN 69 // <<=
#define STARSTAR_ASSIGN 70 // **=
#define SLASHSLASH_ASSIGN 71 // //=
#define PLUS_ASSIGN 72 // +=
#define MINUS_ASSIGN 73 // -=
#define STAR_ASSIGN 74 // *=
#define SLASH_ASSIGN 75 // /=
#define CARET_ASSIGN 76 // ^=
#define PERCENT_ASSIGN 77 // %=
#define LEN 78 //
#define JUMP 79 //
#define IF_BEGIN 80 //
#define ELIF_BEGIN 81 //
#define WHILE_BEGIN 82 //
#define FOR_BEGIN 83 //
#define FUN_CALL 84 //
#define METHOD_CALL 85 //
#define BUILD_TUPLE 86 //
#define BUILD_MATRIX 87 //
#define POP_TOP 88 //
#define ROW 89 //
#define AND 90 //
#define OR 91 //
#define NOT 92 //
#define START 93 //
#define EXPRESSION 94 //
#define ASSIGNMENT 95 //
#define STATEMENT 96 //
#define ASSIGNMENT_EXPRESSION 97 //
#define UNARY_EXPRESSION 98 //
#define BINARY_EXPRESSION 99 //
#define BALANCED_EXPRESSION_LIST 100 //
#define UNBALANCED_EXPRESSION_LIST 101 //
#define ASSIGN_SUBSCRIPT 102 //
#define LOAD_SUBSCRIPT 103 //
#define TOKEN_LIST_AS_STRINGS()\
"UNKNOWN",\
"NIL",\
"LOGIC",\
"INT",\
"DOUBLE",\
"COMPLEX",\
"STRING",\
"MATRIX",\
"TUPLE",\
"CSTRING",\
"CFUN",\
"FUN",\
"CSTRUCT",\
"IDENTIFIER",\
"RANGE",\
"MONATRIX",\
"NUPLE",\
"MONUPLE",\
"ARRAY",\
"LINKED_LIST",\
"CMODULE",\
"GARBAGE",\
"FIELD",\
"END",\
"FUN_MAKE",\
"ELIF",\
"ELSE",\
"WHILE",\
"FOR",\
"BREAK",\
"CONT",\
"LOAD",\
"IF",\
"RETURN",\
"NEWLINE",\
"LPARA",\
"RPARA",\
"LBRACK",\
"RBRACK",\
"LBRACE",\
"RBRACE",\
"UMINUS",\
"UPLUS",\
"TILDE",\
"COLON",\
"COMMA",\
"DOT",\
"SEMICOLON",\
"R_SHIFT",\
"L_SHIFT",\
"STARSTAR",\
"SLASHSLASH",\
"PLUS",\
"MINUS",\
"STAR",\
"SLASH",\
"CARET",\
"PERCENT",\
"LO_EQ",\
"GR_EQ",\
"EQ_EQ",\
"NOT_EQ",\
"LOWER",\
"GREATER",\
"PIPE",\
"AMPERSAND",\
"EXCLAMATION",\
"ASSIGN",\
"R_SHIFT_ASSIGN",\
"L_SHIFT_ASSIGN",\
"STARSTAR_ASSIGN",\
"SLASHSLASH_ASSIGN",\
"PLUS_ASSIGN",\
"MINUS_ASSIGN",\
"STAR_ASSIGN",\
"SLASH_ASSIGN",\
"CARET_ASSIGN",\
"PERCENT_ASSIGN",\
"LEN",\
"JUMP",\
"IF_BEGIN",\
"ELIF_BEGIN",\
"WHILE_BEGIN",\
"FOR_BEGIN",\
"FUN_CALL",\
"METHOD_CALL",\
"BUILD_TUPLE",\
"BUILD_MATRIX",\
"POP_TOP",\
"ROW",\
"AND",\
"OR",\
"NOT",\
"START",\
"EXPRESSION",\
"ASSIGNMENT",\
"STATEMENT",\
"ASSIGNMENT_EXPRESSION",\
"UNARY_EXPRESSION",\
"BINARY_EXPRESSION",\
"BALANCED_EXPRESSION_LIST",\
"UNBALANCED_EXPRESSION_LIST",\
"ASSIGN_SUBSCRIPT",\
"LOAD_SUBSCRIPT",\
//TOKENS_END

extern const char * object_name_array[];
extern const token_struct operator_token_array[];
extern const token_struct reserved_words_token_array[];

fbgc_token get_operator_code(const char *str);
fbgc_token get_operator_code_from_substr(const char *str1,const char *str2);
fbgc_token get_reserved_word_code(const char *str);
fbgc_token get_reserved_word_code_from_substr(const char *str1,const char *str2);


const char * get_token_as_str(fbgc_token tok);


#define is_fbgc_OPERATOR(T)(T>=UMINUS && T< LEN )
#define is_fbgc_IDENTIFIER(T)(T == IDENTIFIER)
#define is_fbgc_ATOM(T)(T>= LOGIC && T<=STRING)
#define is_fbgc_INT(T) (T == INT)
#define is_fbgc_DOUBLE(T) (T == DOUBLE)
#define is_fbgc_STRING(T) (T == STRING)
#define is_fbgc_PARA(T)(T>=LPARA && T<= RBRACK)
#define is_fbgc_UNARY_OPERATOR(T)( T == EXCLAMATION || T== TILDE || T == UPLUS || T == UMINUS)
#define is_fbgc_ASSIGNMENT_OPERATOR(T)( T >= ASSIGN && T< LEN)
//solve this colon issue..
#define is_fbgc_BINARY_OPERATOR(T)( T>=R_SHIFT && T<= AMPERSAND || T == COLON  )


#define is_fbgc_MATRIX(x)(x == MATRIX || x == BUILD_MATRIX)
#define is_fbgc_TUPLE(x)(x == NUPLE || x == MONUPLE ||x == BUILD_TUPLE || x == TUPLE)

#define is_fbgc_FUNCTIONABLE(x)(x == IF || x == ELIF || x == ELSE || x == WHILE || x == FUN || x == LOAD)

#define is_fbgc_EXPRESSION(x)(is_fbgc_ATOM(x) || is_fbgc_IDENTIFIER(x)|| x == EXPRESSION || x == UNARY_EXPRESSION ||x==BINARY_EXPRESSION||\
is_fbgc_TUPLE(x) || is_fbgc_MATRIX(x) || x == CFUN || x == SEMICOLON || x == LEN)

#define is_fbgc_JUMP_STATEMENT(x)(x == BREAK || x == CONT)

#define is_fbgc_ASSIGNMENT(x)(x==ASSIGNMENT_EXPRESSION)
#define is_fbgc_STATEMENT(x)(x == STATEMENT || is_fbgc_EXPRESSION(x) || is_fbgc_ASSIGNMENT(x) || is_fbgc_JUMP_STATEMENT(x))

#ifdef  __cplusplus
}
#endif

#endif
