// This file is part of fbgc

// fbgc is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// fbgc is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with fbgc.  If not, see <https://www.gnu.org/licenses/>.
#ifndef TOKENS_H
#define TOKENS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef uint8_t fbgc_token;

typedef struct {
	fbgc_token tokencode;
	const char * name;
}token_struct;


//TOKENS_BEGIN
//Autogenerated by helper/token_creator.py
#define UNKNOWN 0 // Begin with unknown
#define NIL 1 // null or none
#define CONSTANT 2 // did we use?
#define LOGIC 3 // logical true or false
#define INT 4 // int class
#define DOUBLE 5 // double class
#define COMPLEX 6 // complex class
#define STRING 7 // string class
#define MATRIX 8 // matrix class
#define MAP 9 // map class
#define TUPLE 10 // tuple class
#define INSTANCE 11 //
#define CSTRING 12 // raw c strings without length
#define CFUN 13 // c function
#define FUN 14 // builtin fbgc function
#define CLASS 15 //
#define CSTRUCT 16 // 
#define IDENTIFIER 17 // identifiers
#define RANGE 18 // range obj
#define ARRAY 19 //
#define LINKED_LIST 20 //
#define CMODULE 21 //
#define GARBAGE 22 //
#define END 23 // end
#define FUN_MAKE 24 //
#define CLASS_MAKE 25 //
#define ELIF 26 //
#define ELSE 27 //
#define WHILE 28 //
#define FOR 29 //
#define BREAK 30 //
#define CONT 31 //
#define IF 32 //
#define RETURN 33 //
#define NEWLINE 34 //
#define LPARA 35 // (
#define RPARA 36 // )
#define LBRACK 37 // [
#define RBRACK 38 // ]
#define LBRACE 39 // {
#define RBRACE 40 // }
#define COMMA 41 // , -- set1 start
#define DOT 42 // .
#define SEMICOLON 43 // ; 
#define COLON 44 // : set1 finish
#define RSHIFT 45 // >> assignment and binary operators start from here
#define LSHIFT 46 // <<
#define STARSTAR 47 // **
#define SLASHSLASH 48 // //
#define PLUS 49 // +
#define MINUS 50 // -
#define STAR 51 // *
#define SLASH 52 // /
#define CARET 53 // ^
#define PERCENT 54 // % assignment finish
#define LOEQ 55 // <=
#define GREQ 56 // >=
#define EQEQ 57 // ==
#define NOTEQ 58 // !=
#define LOWER 59 // <
#define GREATER 60 // >
#define PIPE 61 // |
#define AMPERSAND 62 // & binary finish
#define EXCLAMATION 63 // !
#define TILDE 64 // ~
#define UPLUS 65 // +
#define UMINUS 66 // -
#define ASSIGN 67 // = assignment ops start from here
#define RSHIFT_ASSIGN 68 // >>=
#define LSHIFT_ASSIGN 69 // <<=
#define STARSTAR_ASSIGN 70 // **=
#define SLASHSLASH_ASSIGN 71 // //=
#define PLUS_ASSIGN 72 // +=
#define MINUS_ASSIGN 73 // -=
#define STAR_ASSIGN 74 // *=
#define SLASH_ASSIGN 75 // /=
#define CARET_ASSIGN 76 // ^=
#define PERCENT_ASSIGN 77 // %=
#define ASSIGN_SUBSCRIPT 78 //
#define LEN 79 //
#define JUMP 80 //
#define FOR_BEGIN 81 //
#define FUN_CALL 82 //
#define KWFUN_CALL 83 //
#define BUILD_TUPLE 84 //
#define BUILD_MATRIX 85 //
#define BUILD_MAP 86 //
#define POP_TOP 87 //
#define ROW 88 //
#define LOAD_SUBSCRIPT 89 //
#define CLASS_CALL 90 //
#define CLASS_SELF 91 //
#define BUILD_FUN_DEFAULT_ARGS 92 //
#define TOKEN_LIST_AS_STRINGS()\
"UNKNOWN",\
"NIL",\
"CONSTANT",\
"LOGIC",\
"INT",\
"DOUBLE",\
"COMPLEX",\
"STRING",\
"MATRIX",\
"MAP",\
"TUPLE",\
"INSTANCE",\
"CSTRING",\
"CFUN",\
"FUN",\
"CLASS",\
"CSTRUCT",\
"IDENTIFIER",\
"RANGE",\
"ARRAY",\
"LINKED_LIST",\
"CMODULE",\
"GARBAGE",\
"END",\
"FUN_MAKE",\
"CLASS_MAKE",\
"ELIF",\
"ELSE",\
"WHILE",\
"FOR",\
"BREAK",\
"CONT",\
"IF",\
"RETURN",\
"NEWLINE",\
"LPARA",\
"RPARA",\
"LBRACK",\
"RBRACK",\
"LBRACE",\
"RBRACE",\
"COMMA",\
"DOT",\
"SEMICOLON",\
"COLON",\
"RSHIFT",\
"LSHIFT",\
"STARSTAR",\
"SLASHSLASH",\
"PLUS",\
"MINUS",\
"STAR",\
"SLASH",\
"CARET",\
"PERCENT",\
"LOEQ",\
"GREQ",\
"EQEQ",\
"NOTEQ",\
"LOWER",\
"GREATER",\
"PIPE",\
"AMPERSAND",\
"EXCLAMATION",\
"TILDE",\
"UPLUS",\
"UMINUS",\
"ASSIGN",\
"RSHIFT_ASSIGN",\
"LSHIFT_ASSIGN",\
"STARSTAR_ASSIGN",\
"SLASHSLASH_ASSIGN",\
"PLUS_ASSIGN",\
"MINUS_ASSIGN",\
"STAR_ASSIGN",\
"SLASH_ASSIGN",\
"CARET_ASSIGN",\
"PERCENT_ASSIGN",\
"ASSIGN_SUBSCRIPT",\
"LEN",\
"JUMP",\
"FOR_BEGIN",\
"FUN_CALL",\
"KWFUN_CALL",\
"BUILD_TUPLE",\
"BUILD_MATRIX",\
"BUILD_MAP",\
"POP_TOP",\
"ROW",\
"LOAD_SUBSCRIPT",\
"CLASS_CALL",\
"CLASS_SELF",\
"BUILD_FUN_DEFAULT_ARGS",\
//TOKENS_END

#define GM_ERROR 0
#define GM_NEWLINE 1
#define GM_ATOM 2
#define GM_ID 3
#define GM_BINOP 4
#define GM_UNOP 5
#define GM_ASSIGNOP 6
#define GM_EXPRESSION 7
#define GM_UNBALANCED_LIST 8
#define GM_BALANCED_LIST 9
#define GM_LPARA 10
#define GM_LBRACK 11
#define GM_LBRACE 12
#define GM_PIPE 13
#define GM_FUNCTIONAL 14
#define GM_MATRIX 15
#define GM_DOT 16
#define GRAMMAR_TOKENS_AS_STRINGS()\
"GM_ERROR",\
"GM_NEWLINE",\
"GM_ATOM",\
"GM_ID",\
"GM_BINOP",\
"GM_UNOP",\
"GM_ASSIGNOP",\
"GM_EXPRESSION",\
"GM_UNBALANCED_LIST",\
"GM_BALANCED_LIST",\
"GM_LPARA",\
"GM_LBRACK",\
"GM_LBRACE",\
"GM_PIPE",\
"GM_FUNCTIONAL",\
"GM_MATRIX",\
"GM_DOT"

extern const char * gm_name_array[];
extern const char * object_name_array[];
extern const token_struct operator_token_array[];
extern const token_struct reserved_words_token_array[];

const char * get_token_as_str(fbgc_token tok);




#define is_fbgc_OPERATOR(T)(T>=COLON && T< ASSIGN_SUBSCRIPT )
#define is_fbgc_IDENTIFIER(T)(T == IDENTIFIER)
#define is_fbgc_ATOM(T)(T>= LOGIC && T<=STRING)

#define is_fbgc_PARA(T)(T>=LPARA && T<= RBRACK)
#define is_fbgc_UNARY_OPERATOR(T)( T >= EXCLAMATION && T<= UMINUS)
#define is_fbgc_ASSIGNMENT_OPERATOR(T)( T >= ASSIGN && T< ASSIGN_SUBSCRIPT)
//solve this colon issue..
#define is_fbgc_BINARY_OPERATOR(T)( T>=COLON && T<= AMPERSAND)

#define is_fbgc_FUNCTIONABLE(x)(x == IF || x == ELIF || x == ELSE || x == WHILE || x == FUN_MAKE || x == FOR)

// #define is_fbgc_EXPRESSION(x)(is_fbgc_ATOM(x) || is_fbgc_IDENTIFIER(x)|| x == EXPRESSION || x == UNARY_EXPRESSION ||x==BINARY_EXPRESSION||\
// is_fbgc_TUPLE(x) || is_fbgc_MATRIX(x) || x == CFUN || x == SEMICOLON || x == LEN)

// #define is_fbgc_JUMP_STATEMENT(x)(x == BREAK || x == CONT)

// #define is_fbgc_ASSIGNMENT(x)(x==ASSIGNMENT_EXPRESSION)
// #define is_fbgc_STATEMENT(x)(x == STATEMENT || is_fbgc_EXPRESSION(x) || is_fbgc_ASSIGNMENT(x) || is_fbgc_JUMP_STATEMENT(x))

#ifdef  __cplusplus
}
#endif

#endif
